<a href="https://colab.research.google.com/github/valesed/GitHub-Repository-for-CPE311/blob/main/Seatwork_7_1_Programming_Exercise_Data_Wrangling_with_Pandas_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Extract only the year

In [ ]:
import pandas as pd

df = pd.read_csv("/content/meteorite-landings.csv")

df['year'] = df['year'].astype(str).str.slice(0,4)
df

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775000, 6.083330)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.183330, 10.233330)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952,54.21667,-113.00000,"(54.216670, -113.000000)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976,16.88333,-99.90000,"(16.883330, -99.900000)"
4,Achiras,370,Valid,L6,780.0,Fell,1902,-33.16667,-64.95000,"(-33.166670, -64.950000)"
...,...,...,...,...,...,...,...,...,...,...
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,1990,29.03700,17.01850,"(29.037000, 17.018500)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,1999,13.78333,8.96667,"(13.783330, 8.966670)"
45713,Zlin,30410,Valid,H4,3.3,Found,1939,49.25000,17.66667,"(49.250000, 17.666670)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,2003,49.78917,41.50460,"(49.789170, 41.504600)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,1976,33.98333,-115.68333,"(33.983330, -115.683330)"

# 2. Convert year to numeric

In [ ]:
df['year'] = pd.to_numeric(df['year'], errors='coerce')
df

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775000, 6.083330)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.183330, 10.233330)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.216670, -113.000000)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976.0,16.88333,-99.90000,"(16.883330, -99.900000)"
4,Achiras,370,Valid,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.166670, -64.950000)"
...,...,...,...,...,...,...,...,...,...,...
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,1990.0,29.03700,17.01850,"(29.037000, 17.018500)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,1999.0,13.78333,8.96667,"(13.783330, 8.966670)"
45713,Zlin,30410,Valid,H4,3.3,Found,1939.0,49.25000,17.66667,"(49.250000, 17.666670)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,2003.0,49.78917,41.50460,"(49.789170, 41.504600)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,1976.0,33.98333,-115.68333,"(33.983330, -115.683330)"

# 3. Create new column: meteorite fell before 1970

In [ ]:
df['before_1970'] = df['year'] < 1970
df

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation,before_1970
0,Aachen,1,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775000, 6.083330)",True
1,Aarhus,2,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.183330, 10.233330)",True
2,Abee,6,Valid,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.216670, -113.000000)",True
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976.0,16.88333,-99.90000,"(16.883330, -99.900000)",False
4,Achiras,370,Valid,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.166670, -64.950000)",True
...,...,...,...,...,...,...,...,...,...,...,...
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,1990.0,29.03700,17.01850,"(29.037000, 17.018500)",False
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,1999.0,13.78333,8.96667,"(13.783330, 8.966670)",False
45713,Zlin,30410,Valid,H4,3.3,Found,1939.0,49.25000,17.66667,"(49.250000, 17.666670)",True
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,2003.0,49.78917,41.50460,"(49.789170, 41.504600)",False
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,1976.0,33.98333,-115.68333,"(33.983330, -115.683330)",False

# 4. Set id as index

In [ ]:
df = df.set_index('id')
df

,name,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
1,Aachen,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775000, 6.083330)",True
2,Aarhus,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.183330, 10.233330)",True
6,Abee,Valid,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.216670, -113.000000)",True
10,Acapulco,Valid,Acapulcoite,1914.0,Fell,1976.0,16.88333,-99.90000,"(16.883330, -99.900000)",False
370,Achiras,Valid,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.166670, -64.950000)",True
...,...,...,...,...,...,...,...,...,...,...
31356,Zillah 002,Valid,Eucrite,172.0,Found,1990.0,29.03700,17.01850,"(29.037000, 17.018500)",False
30409,Zinder,Valid,"Pallasite, ungrouped",46.0,Found,1999.0,13.78333,8.96667,"(13.783330, 8.966670)",False
30410,Zlin,Valid,H4,3.3,Found,1939.0,49.25000,17.66667,"(49.250000, 17.666670)",True
31357,Zubkovsky,Valid,L6,2167.0,Found,2003.0,49.78917,41.50460,"(49.789170, 41.504600)",False
30414,Zulu Queen,Valid,L3.7,200.0,Found,1976.0,33.98333,-115.68333,"(33.983330, -115.683330)",False

# 5. Sort index before using loc

In [ ]:
df = df.sort_index()
df

,name,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
1,Aachen,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775000, 6.083330)",True
2,Aarhus,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.183330, 10.233330)",True
4,Abajo,Valid,H5,331.0,Found,1982.0,26.80000,-105.41667,"(26.800000, -105.416670)",False
5,Abbott,Valid,H3-6,21100.0,Found,1951.0,36.30000,-104.28333,"(36.300000, -104.283330)",True
6,Abee,Valid,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.216670, -113.000000)",True
...,...,...,...,...,...,...,...,...,...,...
57454,Mandalay Spring,Valid,L6,2854.0,Found,2012.0,40.89201,-118.55319,"(40.892010, -118.553190)",False
57455,Antelope,Valid,H4,754.0,Found,2012.0,40.90183,-118.54465,"(40.901830, -118.544650)",False
57456,Northwest Africa 7870,Valid,L4,42.0,Found,2004.0,0.00000,0.00000,"(0.000000, 0.000000)",False
57457,Northwest Africa 7871,Valid,L6,450.0,Found,2004.0,0.00000,0.00000,"(0.000000, 0.000000)",False
57458,Northwest Africa 7873,Valid,H5-6,446.0,Found,2009.0,0.00000,0.00000,"(0.000000, 0.000000)",False

# 6. Extract rows with id between 10036 and 10040

In [ ]:
result = df.loc[10036:10040]
result

,name,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
10036,Enigma,Valid,H4,94.0,Found,1967.0,31.33333,-82.31667,"(31.333330, -82.316670)",True
10037,Enon,Valid,"Iron, ungrouped",763.0,Found,1883.0,39.86667,-83.95000,"(39.866670, -83.950000)",True
10038,Enshi,Valid,H5,8000.0,Fell,1974.0,30.30000,109.50000,"(30.300000, 109.500000)",False
10039,Ensisheim,Valid,LL6,127000.0,Fell,1491.0,47.86667,7.35000,"(47.866670, 7.350000)",True

#bonus

In [ ]:
df[df['year'] > 2026]

,name,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
24125,Ur,Valid,Iron,NaN,Found,2501.0,30.9,46.01667,"(30.900000, 46.016670)",False
57150,Northwest Africa 7701,Valid,CK6,55.0,Found,2101.0,0.0,0.00000,"(0.000000, 0.000000)",False

# **CONCLUSION**
# **In this activity, I learned several data processing techniques using Pandas. These include cleaning data by extracting specific parts, converting values to numeric format, and creating new columns based on conditions. I also practiced organizing data by setting a column and sorting it. Finally, I learned how to retrieve specific rows and how to identify possible data errors or missing values in a dataset**